version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      TZ: America/Argentina/Cordoba

  cron:
    container_name: cmc_cron
    build:
      context: ./cron
    restart: unless-stopped
    depends_on:
      - fastapi
    env_file:
      - .env
    environment:
      API_URL: http://fastapi:8000

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      UPLOAD_LIMIT: 100M

volumes:
  mysql_data:
