"""Arreglos en los constraint de LiquidacionDetalle

Revision ID: 02bd96bcac31
Revises: 7fe681d4fdd9
Create Date: 2025-09-07 19:26:45.199654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bd96bcac31'
down_revision: Union[str, Sequence[str], None] = '7fe681d4fdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_det_prest_en_liq'), 'detalle_liquidacion', type_='unique')
    op.create_unique_constraint('uq_det_prest_en_liq', 'detalle_liquidacion', ['prestacion_id', 'liquidacion_id', 'medico_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_det_prest_en_liq', 'detalle_liquidacion', type_='unique')
    op.create_unique_constraint(op.f('uq_det_prest_en_liq'), 'detalle_liquidacion', ['prestacion_id', 'liquidacion_id'])
    # ### end Alembic commands ###
