"""Se agrego el campo de estado en Liquidacion

Revision ID: 1b9d8248844d
Revises: 74155866b29a
Create Date: 2025-09-08 10:33:59.324089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9d8248844d'
down_revision: Union[str, Sequence[str], None] = '74155866b29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidacion', sa.Column('estado', sa.Enum('A', 'C', name='liq_estado'), server_default='A', nullable=False))
    op.add_column('liquidacion', sa.Column('cierre_timestamp', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_liquidacion_estado'), 'liquidacion', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidacion_estado'), table_name='liquidacion')
    op.drop_column('liquidacion', 'cierre_timestamp')
    op.drop_column('liquidacion', 'estado')
    # ### end Alembic commands ###
