"""Agregacion de nuevos modelos para la decuccion y sus calculos

Revision ID: 2628f32ae9e3
Revises: e6650ac0a460
Create Date: 2025-09-15 07:56:43.320048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2628f32ae9e3'
down_revision: Union[str, Sequence[str], None] = 'e6650ac0a460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion_aplicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('desc', 'esp', name='ded_apl_tipo'), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['resumen_id'], ['liquidacion_resumen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resumen_id', 'medico_id', 'concepto_tipo', 'concepto_id', name='uq_apl_res_med_concepto')
    )
    op.create_index(op.f('ix_deduccion_aplicacion_concepto_id'), 'deduccion_aplicacion', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_concepto_tipo'), 'deduccion_aplicacion', ['concepto_tipo'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_medico_id'), 'deduccion_aplicacion', ['medico_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_resumen_id'), 'deduccion_aplicacion', ['resumen_id'], unique=False)
    op.create_table('deduccion_saldo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('desc', 'esp', name='ded_saldo_tipo'), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'concepto_tipo', 'concepto_id', name='uq_saldo_med_concepto')
    )
    op.create_index(op.f('ix_deduccion_saldo_concepto_id'), 'deduccion_saldo', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_concepto_tipo'), 'deduccion_saldo', ['concepto_tipo'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_medico_id'), 'deduccion_saldo', ['medico_id'], unique=False)
    op.add_column('deducciones_colegio', sa.Column('calculado_total', sa.DECIMAL(precision=14, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deducciones_colegio', 'calculado_total')
    op.drop_index(op.f('ix_deduccion_saldo_medico_id'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_tipo'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_id'), table_name='deduccion_saldo')
    op.drop_table('deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_aplicacion_resumen_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_medico_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_concepto_tipo'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_concepto_id'), table_name='deduccion_aplicacion')
    op.drop_table('deduccion_aplicacion')
    # ### end Alembic commands ###
