"""Campos de auditoria

Revision ID: 2db31684d368
Revises: be42759d37e9
Create Date: 2025-09-19 22:05:04.770927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2db31684d368'
down_revision: Union[str, Sequence[str], None] = 'be42759d37e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debito_credito', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('debito_credito', 'created_by_user',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_debito_credito_created_by_user'), 'debito_credito', ['created_by_user'], unique=False)
    op.drop_column('debito_credito', 'creado_timestamp')
    op.add_column('deduccion_aplicacion', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('deduccion_aplicacion', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_deduccion_aplicacion_created_by_user'), 'deduccion_aplicacion', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'deduccion_aplicacion', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('deduccion_saldo', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('deduccion_saldo', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_deduccion_saldo_created_by_user'), 'deduccion_saldo', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'deduccion_saldo', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('deducciones_colegio', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('deducciones_colegio', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_deducciones_colegio_created_by_user'), 'deducciones_colegio', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'deducciones_colegio', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('descuentos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('descuentos', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_descuentos_created_by_user'), 'descuentos', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'descuentos', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('detalle_liquidacion', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('detalle_liquidacion', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_detalle_liquidacion_created_by_user'), 'detalle_liquidacion', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'detalle_liquidacion', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('liquidacion', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('liquidacion', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_liquidacion_created_by_user'), 'liquidacion', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'liquidacion', 'listado_medico', ['created_by_user'], ['ID'])
    op.add_column('liquidacion_resumen', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('liquidacion_resumen', sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True))
    op.create_index(op.f('ix_liquidacion_resumen_created_by_user'), 'liquidacion_resumen', ['created_by_user'], unique=False)
    op.create_foreign_key(None, 'liquidacion_resumen', 'listado_medico', ['created_by_user'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'liquidacion_resumen', type_='foreignkey')
    op.drop_index(op.f('ix_liquidacion_resumen_created_by_user'), table_name='liquidacion_resumen')
    op.drop_column('liquidacion_resumen', 'created_by_user')
    op.drop_column('liquidacion_resumen', 'created_at')
    op.drop_constraint(None, 'liquidacion', type_='foreignkey')
    op.drop_index(op.f('ix_liquidacion_created_by_user'), table_name='liquidacion')
    op.drop_column('liquidacion', 'created_by_user')
    op.drop_column('liquidacion', 'created_at')
    op.drop_constraint(None, 'detalle_liquidacion', type_='foreignkey')
    op.drop_index(op.f('ix_detalle_liquidacion_created_by_user'), table_name='detalle_liquidacion')
    op.drop_column('detalle_liquidacion', 'created_by_user')
    op.drop_column('detalle_liquidacion', 'created_at')
    op.drop_constraint(None, 'descuentos', type_='foreignkey')
    op.drop_index(op.f('ix_descuentos_created_by_user'), table_name='descuentos')
    op.drop_column('descuentos', 'created_by_user')
    op.drop_column('descuentos', 'created_at')
    op.drop_constraint(None, 'deducciones_colegio', type_='foreignkey')
    op.drop_index(op.f('ix_deducciones_colegio_created_by_user'), table_name='deducciones_colegio')
    op.drop_column('deducciones_colegio', 'created_by_user')
    op.drop_column('deducciones_colegio', 'created_at')
    op.drop_constraint(None, 'deduccion_saldo', type_='foreignkey')
    op.drop_index(op.f('ix_deduccion_saldo_created_by_user'), table_name='deduccion_saldo')
    op.drop_column('deduccion_saldo', 'created_by_user')
    op.drop_column('deduccion_saldo', 'created_at')
    op.drop_constraint(None, 'deduccion_aplicacion', type_='foreignkey')
    op.drop_index(op.f('ix_deduccion_aplicacion_created_by_user'), table_name='deduccion_aplicacion')
    op.drop_column('deduccion_aplicacion', 'created_by_user')
    op.drop_column('deduccion_aplicacion', 'created_at')
    op.add_column('debito_credito', sa.Column('creado_timestamp', mysql.VARCHAR(length=25), nullable=True))
    op.drop_index(op.f('ix_debito_credito_created_by_user'), table_name='debito_credito')
    op.alter_column('debito_credito', 'created_by_user',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('debito_credito', 'created_at')
    # ### end Alembic commands ###
