"""init:modelos v1

Revision ID: 2ea8bd41d52a
Revises: 8623c97f5343
Create Date: 2025-07-25 10:11:24.498049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ea8bd41d52a'
down_revision: Union[str, Sequence[str], None] = '8623c97f5343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodos', 'version',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Versión del período; se incrementa al reabrir',
               existing_comment='——— WEPSSS ——— Versión del período; se incrementa al reabrir',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodos', 'version',
               existing_type=mysql.INTEGER(display_width=11),
               comment='——— WEPSSS ——— Versión del período; se incrementa al reabrir',
               existing_comment='Versión del período; se incrementa al reabrir',
               existing_nullable=False)
    # ### end Alembic commands ###
