"""Modificaciones en el modelo de DetalleLiquidacion

Revision ID: 4253f7f33d7c
Revises: 02bd96bcac31
Create Date: 2025-09-08 02:26:53.784443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4253f7f33d7c'
down_revision: Union[str, Sequence[str], None] = '02bd96bcac31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_liquidacion', sa.Column('debito_credito_id', sa.Integer(), nullable=True))
    op.add_column('detalle_liquidacion', sa.Column('pagado', sa.DECIMAL(precision=14, scale=2), nullable=False))
    op.create_index(op.f('ix_detalle_liquidacion_debito_credito_id'), 'detalle_liquidacion', ['debito_credito_id'], unique=False)
    op.create_foreign_key(None, 'detalle_liquidacion', 'debito_credito', ['debito_credito_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_liquidacion', type_='foreignkey')
    op.drop_index(op.f('ix_detalle_liquidacion_debito_credito_id'), table_name='detalle_liquidacion')
    op.drop_column('detalle_liquidacion', 'pagado')
    op.drop_column('detalle_liquidacion', 'debito_credito_id')
    # ### end Alembic commands ###
