"""mejoras en el diseño de Liquidacion y DetalleLiquidacion

Revision ID: 5611a8be8fb9
Revises: 0c92a4d351cc
Create Date: 2025-09-07 18:13:37.454336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5611a8be8fb9'
down_revision: Union[str, Sequence[str], None] = '0c92a4d351cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("SET @OLD_FK_CHECKS := @@FOREIGN_KEY_CHECKS")
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)

    # ------------ detalle_liquidacion: columnas actuales ------------
    cols = {c["name"] for c in insp.get_columns("detalle_liquidacion")}

    # 1) ADD prev_detalle_id si NO existe
    if "prev_detalle_id" not in cols:
        op.add_column(
            "detalle_liquidacion",
            sa.Column("prev_detalle_id", sa.Integer(), nullable=True),
        )

    # 2) FK self-ref a detalle_liquidacion(prev_detalle_id -> id) SOLO si no existe
    fk_names = {fk["name"] for fk in insp.get_foreign_keys("detalle_liquidacion")}
    if "detalle_liquidacion_prev_fk" not in fk_names:
        # nombrá la FK para poder manejarla a futuro
        op.create_foreign_key(
            "detalle_liquidacion_prev_fk",
            "detalle_liquidacion",
            "detalle_liquidacion",
            ["prev_detalle_id"],
            ["id"],
        )

    # 3) Crear índices/unique nuevos si hiciera falta (idempotente)
    idx_names = {ix["name"] for ix in insp.get_indexes("detalle_liquidacion")}
    if "idx_det_os_liq_med" not in idx_names:
        op.create_index(
            "idx_det_os_liq_med",
            "detalle_liquidacion",
            ["obra_social_id", "liquidacion_id", "medico_id"],
            unique=False,
        )
    if "idx_det_prest" not in idx_names:
        op.create_index("idx_det_prest", "detalle_liquidacion", ["prestacion_id"], unique=False)

    uq_names = {uq["name"] for uq in insp.get_unique_constraints("detalle_liquidacion")}
    if "uq_det_prest_en_liq" not in uq_names:
        op.create_unique_constraint(
            "uq_det_prest_en_liq",
            "detalle_liquidacion",
            ["prestacion_id", "liquidacion_id"],
        )

    # 4) BORRAR la columna debito_credito_id SOLO si existe,
    #    y ANTES tirar todas las FKs e índices que la usan
    if "debito_credito_id" in cols:
        # dropear FKs que apunten a esa columna
        for fk in insp.get_foreign_keys("detalle_liquidacion"):
            if "debito_credito_id" in (fk.get("constrained_columns") or []):
                op.drop_constraint(fk["name"], "detalle_liquidacion", type_="foreignkey")

        # dropear índices (incl. únicos) que la incluyan
        for ix in insp.get_indexes("detalle_liquidacion"):
            if "debito_credito_id" in (ix.get("column_names") or []):
                op.drop_index(ix["name"], table_name="detalle_liquidacion")

        # algunos MySQL crean índice implícito con el mismo nombre
        try:
            op.execute("ALTER TABLE detalle_liquidacion DROP INDEX debito_credito_id")
        except Exception:
            pass

        # finalmente, dropear la columna
        with op.batch_alter_table("detalle_liquidacion") as batch:
            batch.drop_column("debito_credito_id")

    # 5) Otras columnas tuyas (neto, deduccion_monto, bruto, debito_monto)
    cols = {c["name"] for c in insp.get_columns("detalle_liquidacion")}  # refrescar
    for col in ("neto", "deduccion_monto", "bruto", "debito_monto"):
        if col in cols:
            with op.batch_alter_table("detalle_liquidacion") as batch:
                batch.drop_column(col)

    # 6) Agregar 'importe' si no existe
    if "importe" not in cols:
        op.add_column(
            "detalle_liquidacion",
            sa.Column("importe", sa.DECIMAL(14, 2), nullable=False),
        )

    # 7) LIQUIDACION: agregar 'version' si no existe, y manejar índices idempotentes
    cols_liq = {c["name"] for c in insp.get_columns("liquidacion")}
    if "version" not in cols_liq:
        op.add_column("liquidacion", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
        op.execute("ALTER TABLE liquidacion ALTER COLUMN version DROP DEFAULT")

    idx_liq = {ix["name"] for ix in insp.get_indexes("liquidacion")}
    if "resumen_id" in idx_liq:
        op.drop_index("resumen_id", table_name="liquidacion")
    if "idx_liq_os_per_version" not in idx_liq:
        op.create_index("idx_liq_os_per_version", "liquidacion", ["obra_social_id", "anio_periodo", "mes_periodo", "version"])
    if "idx_liq_res_os_per" not in idx_liq:
        op.create_index("idx_liq_res_os_per", "liquidacion", ["resumen_id", "obra_social_id", "mes_periodo", "anio_periodo"])
    op.execute("SET FOREIGN_KEY_CHECKS=@OLD_FK_CHECKS")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_liq_res_os_per', table_name='liquidacion')
    op.drop_index('idx_liq_os_per_version', table_name='liquidacion')
    op.create_index(op.f('resumen_id'), 'liquidacion', ['obra_social_id', 'mes_periodo', 'anio_periodo'], unique=False)
    op.drop_column('liquidacion', 'version')
    op.add_column('detalle_liquidacion', sa.Column('debito_monto', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('detalle_liquidacion', sa.Column('bruto', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('detalle_liquidacion', sa.Column('deduccion_monto', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('detalle_liquidacion', sa.Column('neto', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('detalle_liquidacion', sa.Column('debito_credito_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'detalle_liquidacion', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_liquidacion_ibfk_11'), 'detalle_liquidacion', 'debito_credito', ['debito_credito_id'], ['id'])
    op.drop_constraint('uq_det_prest_en_liq', 'detalle_liquidacion', type_='unique')
    op.drop_index('idx_det_prest', table_name='detalle_liquidacion')
    op.drop_index('idx_det_os_liq_med', table_name='detalle_liquidacion')
    op.create_index(op.f('uq_det_prestacion'), 'detalle_liquidacion', ['prestacion_id'], unique=True)
    op.create_index(op.f('idx_det_os_per_med'), 'detalle_liquidacion', ['obra_social_id', 'liquidacion_id', 'medico_id'], unique=False)
    op.drop_column('detalle_liquidacion', 'importe')
    op.drop_column('detalle_liquidacion', 'prev_detalle_id')
    # ### end Alembic commands ###
