"""Campos de auditoria

Revision ID: 619e0b2aabc8
Revises: 2db31684d368
Create Date: 2025-09-19 22:06:45.039928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '619e0b2aabc8'
down_revision: Union[str, Sequence[str], None] = '2db31684d368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liquidacion_resumen', 'cierre_timestamp')
    op.drop_column('liquidacion_resumen', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidacion_resumen', sa.Column('estado', mysql.ENUM('a', 'c', 'e'), nullable=False))
    op.add_column('liquidacion_resumen', sa.Column('cierre_timestamp', mysql.VARCHAR(length=25), nullable=True))
    # ### end Alembic commands ###
