"""sync liquidacion/deducciones schemas

Revision ID: 67154838144e
Revises: 
Create Date: 2026-01-23 14:51:22.238609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67154838144e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion_saldo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('desc', 'esp', name='ded_saldo_tipo'), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'concepto_tipo', 'concepto_id', name='uq_saldo_med_concepto')
    )
    op.create_index(op.f('ix_deduccion_saldo_concepto_id'), 'deduccion_saldo', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_concepto_tipo'), 'deduccion_saldo', ['concepto_tipo'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_created_by_user'), 'deduccion_saldo', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_medico_id'), 'deduccion_saldo', ['medico_id'], unique=False)
    op.drop_index(op.f('idx_exp_desc_nro_socio'), table_name='export_descuentos')
    op.drop_index(op.f('idx_exp_desc_periodo'), table_name='export_descuentos')
    op.drop_index(op.f('idx_exp_desc_servicio'), table_name='export_descuentos')
    op.drop_table('export_descuentos')
    op.drop_index(op.f('uq_apl_per_med_desc'), table_name='deduccion_aplicacion')
    op.drop_column('liquidacion_resumen', 'total_debitos')
    op.drop_column('liquidacion_resumen', 'total_deduccion')
    op.drop_column('liquidacion_resumen', 'total_bruto')
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=mysql.VARCHAR(length=66),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=8, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=69),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=mysql.VARCHAR(length=23),
               type_=sa.String(length=25, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False,
               comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR',
               existing_comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación')
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index('CATEGORIA', 'listado_medico', ['CATEGORIA'], unique=False)
    op.create_index('NRO_ESPECIALIDAD', 'listado_medico', ['NRO_ESPECIALIDAD'], unique=False)
    op.create_index('NRO_ESPECIALIDAD2', 'listado_medico', ['NRO_ESPECIALIDAD2'], unique=False)
    op.create_index('NRO_ESPECIALIDAD3', 'listado_medico', ['NRO_ESPECIALIDAD3'], unique=False)
    op.create_index('NRO_ESPECIALIDAD4', 'listado_medico', ['NRO_ESPECIALIDAD4'], unique=False)
    op.create_index('NRO_ESPECIALIDAD5', 'listado_medico', ['NRO_ESPECIALIDAD5'], unique=False)
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('periodos_doctor', 'USUARIO')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodos_doctor', sa.Column('USUARIO', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index('NRO_ESPECIALIDAD5', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD4', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD3', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD2', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD', table_name='listado_medico')
    op.drop_index('CATEGORIA', table_name='listado_medico')
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True,
               comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación',
               existing_comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR')
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=sa.String(length=25, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=23),
               nullable=True)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=69),
               nullable=True)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=sa.String(length=8, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=66),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               nullable=True)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('liquidacion_resumen', sa.Column('total_bruto', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('liquidacion_resumen', sa.Column('total_deduccion', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('liquidacion_resumen', sa.Column('total_debitos', mysql.DECIMAL(precision=14, scale=2), nullable=False))
    op.create_index(op.f('uq_apl_per_med_desc'), 'deduccion_aplicacion', ['anio', 'mes', 'medico_id', 'descuento_id'], unique=True)
    op.create_table('export_descuentos',
    sa.Column('ssd_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('modified', mysql.DATETIME(), nullable=False),
    sa.Column('anio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('saldo', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('servicio_nro_colegio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nro_socio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ssd_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_exp_desc_servicio'), 'export_descuentos', ['servicio_nro_colegio'], unique=False)
    op.create_index(op.f('idx_exp_desc_periodo'), 'export_descuentos', ['anio', 'mes'], unique=False)
    op.create_index(op.f('idx_exp_desc_nro_socio'), 'export_descuentos', ['nro_socio'], unique=False)
    op.drop_index(op.f('ix_deduccion_saldo_medico_id'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_created_by_user'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_tipo'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_id'), table_name='deduccion_saldo')
    op.drop_table('deduccion_saldo')
    # ### end Alembic commands ###
