"""Cambios

Revision ID: 6bd404354968
Revises: 2628f32ae9e3
Create Date: 2025-09-17 03:09:55.530096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bd404354968'
down_revision: Union[str, Sequence[str], None] = '2628f32ae9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afiliados')
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_table('afiliados',
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('modified', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nro_documento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nombre_apellido', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('estado_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='1=>activo,2=>baja,3=>no_existe'),
    sa.Column('rutina_corrio', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
