"""Mas modificaciones

Revision ID: 74155866b29a
Revises: 4253f7f33d7c
Create Date: 2025-09-08 03:38:28.491931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74155866b29a'
down_revision: Union[str, Sequence[str], None] = '4253f7f33d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('debito_credito_ibfk_2'), 'debito_credito', type_='foreignkey')
    op.create_foreign_key(None, 'debito_credito', 'guardar_atencion', ['id_atencion'], ['ID'], ondelete='CASCADE')
    op.drop_constraint(op.f('detalle_liquidacion_ibfk_15'), 'detalle_liquidacion', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_liquidacion', 'debito_credito', ['debito_credito_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_liquidacion', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_liquidacion_ibfk_15'), 'detalle_liquidacion', 'debito_credito', ['debito_credito_id'], ['id'])
    op.drop_constraint(None, 'debito_credito', type_='foreignkey')
    op.create_foreign_key(op.f('debito_credito_ibfk_2'), 'debito_credito', 'guardar_atencion', ['id_atencion'], ['ID'])
    # ### end Alembic commands ###
