"""repoblacion de tablas

Revision ID: 7728154b4c66
Revises: 
Create Date: 2025-11-12 02:49:17.265353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7728154b4c66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('resumen', sa.String(length=1000), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('publicada', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('portada', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_noticias_publicada_fecha', 'noticias', ['publicada', 'fecha_creacion'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('publicidad_medicos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('medico_id', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('adjunto_filename', sa.String(length=255), nullable=True),
    sa.Column('adjunto_content_type', sa.String(length=120), nullable=True),
    sa.Column('adjunto_size', sa.BigInteger(), nullable=True),
    sa.Column('adjunto_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicidad_medicos_medico_id'), 'publicidad_medicos', ['medico_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('debito_credito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('d', 'c', name='debcre_tipo'), nullable=False),
    sa.Column('id_atencion', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('obra_social_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['id_atencion'], ['guardar_atencion.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obra_social_id'], ['obras_sociales.NRO_OBRASOCIAL'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debito_credito_created_by_user'), 'debito_credito', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_debito_credito_id_atencion'), 'debito_credito', ['id_atencion'], unique=False)
    op.create_index(op.f('ix_debito_credito_obra_social_id'), 'debito_credito', ['obra_social_id'], unique=False)
    op.create_index(op.f('ix_debito_credito_periodo'), 'debito_credito', ['periodo'], unique=False)
    op.create_table('deduccion_saldo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('desc', 'esp', name='ded_saldo_tipo'), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'concepto_tipo', 'concepto_id', name='uq_saldo_med_concepto')
    )
    op.create_index(op.f('ix_deduccion_saldo_concepto_id'), 'deduccion_saldo', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_concepto_tipo'), 'deduccion_saldo', ['concepto_tipo'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_created_by_user'), 'deduccion_saldo', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deduccion_saldo_medico_id'), 'deduccion_saldo', ['medico_id'], unique=False)
    op.create_table('descuentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nro_colegio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descuentos_created_by_user'), 'descuentos', ['created_by_user'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_medico_id'), 'documentos', ['medico_id'], unique=False)
    op.create_table('documentos_noticias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_noticias_noticia_id'), 'documentos_noticias', ['noticia_id'], unique=False)
    op.create_table('liquidacion_resumen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('total_bruto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_debitos', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_deduccion', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', name='uq_liqres_anio_mes')
    )
    op.create_index(op.f('ix_liquidacion_resumen_created_by_user'), 'liquidacion_resumen', ['created_by_user'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('solicitudes_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_solicitud'), server_default='pendiente', nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_registros_estado'), 'solicitudes_registros', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_registros_medico_id'), 'solicitudes_registros', ['medico_id'], unique=False)
    op.create_table('user_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['listado_medico.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['listado_medico.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('deduccion_aplicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('desc', 'esp', name='ded_apl_tipo'), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['resumen_id'], ['liquidacion_resumen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resumen_id', 'medico_id', 'concepto_tipo', 'concepto_id', name='uq_apl_res_med_concepto')
    )
    op.create_index(op.f('ix_deduccion_aplicacion_concepto_id'), 'deduccion_aplicacion', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_concepto_tipo'), 'deduccion_aplicacion', ['concepto_tipo'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_created_by_user'), 'deduccion_aplicacion', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_medico_id'), 'deduccion_aplicacion', ['medico_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_resumen_id'), 'deduccion_aplicacion', ['resumen_id'], unique=False)
    op.create_table('deducciones_colegio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=True),
    sa.Column('especialidad_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('monto_aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_aplicado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('calculado_total', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['descuento_id'], ['descuentos.id'], ),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.ID'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['resumen_id'], ['liquidacion_resumen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'resumen_id', 'descuento_id', name='uq_med_res_desc'),
    sa.UniqueConstraint('medico_id', 'resumen_id', 'especialidad_id', name='uq_med_res_esp2')
    )
    op.create_index('idx_med_res', 'deducciones_colegio', ['medico_id', 'resumen_id'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_created_by_user'), 'deducciones_colegio', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_descuento_id'), 'deducciones_colegio', ['descuento_id'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_especialidad_id'), 'deducciones_colegio', ['especialidad_id'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_medico_id'), 'deducciones_colegio', ['medico_id'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_resumen_id'), 'deducciones_colegio', ['resumen_id'], unique=False)
    op.create_table('liquidacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('mes_periodo', sa.Integer(), nullable=False),
    sa.Column('anio_periodo', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('A', 'C', name='liq_estado'), server_default='A', nullable=False),
    sa.Column('cierre_timestamp', sa.String(length=25), nullable=True),
    sa.Column('nro_liquidacion', sa.String(length=30), nullable=True),
    sa.Column('total_bruto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_debitos', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_neto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['resumen_id'], ['liquidacion_resumen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resumen_id', 'obra_social_id', 'mes_periodo', 'anio_periodo', 'version', name='uq_liq_res_os_per_v2')
    )
    op.create_index('idx_liq_os_per_version', 'liquidacion', ['obra_social_id', 'anio_periodo', 'mes_periodo', 'version'], unique=False)
    op.create_index('idx_liq_res_os_per', 'liquidacion', ['resumen_id', 'obra_social_id', 'mes_periodo', 'anio_periodo'], unique=False)
    op.create_index(op.f('ix_liquidacion_created_by_user'), 'liquidacion', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_liquidacion_estado'), 'liquidacion', ['estado'], unique=False)
    op.create_index(op.f('ix_liquidacion_obra_social_id'), 'liquidacion', ['obra_social_id'], unique=False)
    op.create_table('detalle_liquidacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('prestacion_id', sa.String(length=16), nullable=False),
    sa.Column('prev_detalle_id', sa.Integer(), nullable=True),
    sa.Column('debito_credito_id', sa.Integer(), nullable=True),
    sa.Column('pagado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('importe', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['debito_credito_id'], ['debito_credito.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.ForeignKeyConstraint(['prev_detalle_id'], ['detalle_liquidacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestacion_id', 'liquidacion_id', 'medico_id', name='uq_det_prest_en_liq')
    )
    op.create_index('idx_det_os_liq_med', 'detalle_liquidacion', ['obra_social_id', 'liquidacion_id', 'medico_id'], unique=False)
    op.create_index('idx_det_prest', 'detalle_liquidacion', ['prestacion_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_created_by_user'), 'detalle_liquidacion', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_debito_credito_id'), 'detalle_liquidacion', ['debito_credito_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_liquidacion_id'), 'detalle_liquidacion', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_medico_id'), 'detalle_liquidacion', ['medico_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_obra_social_id'), 'detalle_liquidacion', ['obra_social_id'], unique=False)
    op.drop_table('exepcion')
    op.drop_column('avisos', 'AVISO_PLANILLA')
    op.add_column('espe_cod_swiss', sa.Column('C_P_H_S', sa.String(length=1, collation='utf8_spanish2_ci'), server_default=sa.text("'C'"), nullable=False))
    op.create_index('CODIGO', 'espe_cod_swiss', ['CODIGO'], unique=False)
    op.create_index('C_P_H_S', 'espe_cod_swiss', ['C_P_H_S'], unique=False)
    op.drop_column('espe_cod_swiss', 'ID_ESPE')
    op.add_column('listado_medico', sa.Column('conceps_espec', sa.JSON(), nullable=False))
    op.add_column('listado_medico', sa.Column('cbu', sa.String(length=50, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('nro_resolucion', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('fecha_resolucion', sa.Date(), nullable=True))
    op.add_column('listado_medico', sa.Column('apellido', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('nombre_', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('titulo', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('localidad', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('condicion_impositiva', sa.String(length=70, collation='utf8_spanish2_ci'), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_titulo', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_matricula_nac', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_matricula_prov', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_resolucion', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_habilitacion_municipal', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_cuit', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_condicion_impositiva', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_anssal', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_malapraxis', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_cbu', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('attach_dni', sa.String(length=512), nullable=True))
    op.add_column('listado_medico', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=mysql.VARCHAR(length=66),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=8, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=69),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=mysql.VARCHAR(length=23),
               type_=sa.String(length=25, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False,
               comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR',
               existing_comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación')
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index('CATEGORIA', 'listado_medico', ['CATEGORIA'], unique=False)
    op.create_index('NRO_ESPECIALIDAD', 'listado_medico', ['NRO_ESPECIALIDAD'], unique=False)
    op.create_index('NRO_ESPECIALIDAD2', 'listado_medico', ['NRO_ESPECIALIDAD2'], unique=False)
    op.create_index('NRO_ESPECIALIDAD3', 'listado_medico', ['NRO_ESPECIALIDAD3'], unique=False)
    op.create_index('NRO_ESPECIALIDAD4', 'listado_medico', ['NRO_ESPECIALIDAD4'], unique=False)
    op.create_index('NRO_ESPECIALIDAD5', 'listado_medico', ['NRO_ESPECIALIDAD5'], unique=False)
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('periodos_doctor', 'USUARIO')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodos_doctor', sa.Column('USUARIO', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index('NRO_ESPECIALIDAD5', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD4', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD3', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD2', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD', table_name='listado_medico')
    op.drop_index('CATEGORIA', table_name='listado_medico')
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True,
               comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación',
               existing_comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR')
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=sa.String(length=25, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=23),
               nullable=True)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=69),
               nullable=True)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=sa.String(length=8, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=66),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               nullable=True)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('listado_medico', 'hashed_password')
    op.drop_column('listado_medico', 'attach_dni')
    op.drop_column('listado_medico', 'attach_cbu')
    op.drop_column('listado_medico', 'attach_malapraxis')
    op.drop_column('listado_medico', 'attach_anssal')
    op.drop_column('listado_medico', 'attach_condicion_impositiva')
    op.drop_column('listado_medico', 'attach_cuit')
    op.drop_column('listado_medico', 'attach_habilitacion_municipal')
    op.drop_column('listado_medico', 'attach_resolucion')
    op.drop_column('listado_medico', 'attach_matricula_prov')
    op.drop_column('listado_medico', 'attach_matricula_nac')
    op.drop_column('listado_medico', 'attach_titulo')
    op.drop_column('listado_medico', 'condicion_impositiva')
    op.drop_column('listado_medico', 'localidad')
    op.drop_column('listado_medico', 'titulo')
    op.drop_column('listado_medico', 'nombre_')
    op.drop_column('listado_medico', 'apellido')
    op.drop_column('listado_medico', 'fecha_resolucion')
    op.drop_column('listado_medico', 'nro_resolucion')
    op.drop_column('listado_medico', 'cbu')
    op.drop_column('listado_medico', 'conceps_espec')
    op.add_column('espe_cod_swiss', sa.Column('ID_ESPE', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_index('C_P_H_S', table_name='espe_cod_swiss')
    op.drop_index('CODIGO', table_name='espe_cod_swiss')
    op.drop_column('espe_cod_swiss', 'C_P_H_S')
    op.add_column('avisos', sa.Column('AVISO_PLANILLA', mysql.VARCHAR(collation='utf8_spanish2_ci', length=1), server_default=sa.text("'A'"), nullable=False, comment='A=AVISOS / P=PLANILLAS DE CONSULTAS'))
    op.create_table('exepcion',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('NRO_SOCIO', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('CODIGO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_detalle_liquidacion_obra_social_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_medico_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_liquidacion_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_debito_credito_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_created_by_user'), table_name='detalle_liquidacion')
    op.drop_index('idx_det_prest', table_name='detalle_liquidacion')
    op.drop_index('idx_det_os_liq_med', table_name='detalle_liquidacion')
    op.drop_table('detalle_liquidacion')
    op.drop_index(op.f('ix_liquidacion_obra_social_id'), table_name='liquidacion')
    op.drop_index(op.f('ix_liquidacion_estado'), table_name='liquidacion')
    op.drop_index(op.f('ix_liquidacion_created_by_user'), table_name='liquidacion')
    op.drop_index('idx_liq_res_os_per', table_name='liquidacion')
    op.drop_index('idx_liq_os_per_version', table_name='liquidacion')
    op.drop_table('liquidacion')
    op.drop_index(op.f('ix_deducciones_colegio_resumen_id'), table_name='deducciones_colegio')
    op.drop_index(op.f('ix_deducciones_colegio_medico_id'), table_name='deducciones_colegio')
    op.drop_index(op.f('ix_deducciones_colegio_especialidad_id'), table_name='deducciones_colegio')
    op.drop_index(op.f('ix_deducciones_colegio_descuento_id'), table_name='deducciones_colegio')
    op.drop_index(op.f('ix_deducciones_colegio_created_by_user'), table_name='deducciones_colegio')
    op.drop_index('idx_med_res', table_name='deducciones_colegio')
    op.drop_table('deducciones_colegio')
    op.drop_index(op.f('ix_deduccion_aplicacion_resumen_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_medico_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_created_by_user'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_concepto_tipo'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_concepto_id'), table_name='deduccion_aplicacion')
    op.drop_table('deduccion_aplicacion')
    op.drop_table('user_role')
    op.drop_table('user_permission')
    op.drop_index(op.f('ix_solicitudes_registros_medico_id'), table_name='solicitudes_registros')
    op.drop_index(op.f('ix_solicitudes_registros_estado'), table_name='solicitudes_registros')
    op.drop_table('solicitudes_registros')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_liquidacion_resumen_created_by_user'), table_name='liquidacion_resumen')
    op.drop_table('liquidacion_resumen')
    op.drop_index(op.f('ix_documentos_noticias_noticia_id'), table_name='documentos_noticias')
    op.drop_table('documentos_noticias')
    op.drop_index(op.f('ix_documentos_medico_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_descuentos_created_by_user'), table_name='descuentos')
    op.drop_table('descuentos')
    op.drop_index(op.f('ix_deduccion_saldo_medico_id'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_created_by_user'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_tipo'), table_name='deduccion_saldo')
    op.drop_index(op.f('ix_deduccion_saldo_concepto_id'), table_name='deduccion_saldo')
    op.drop_table('deduccion_saldo')
    op.drop_index(op.f('ix_debito_credito_periodo'), table_name='debito_credito')
    op.drop_index(op.f('ix_debito_credito_obra_social_id'), table_name='debito_credito')
    op.drop_index(op.f('ix_debito_credito_id_atencion'), table_name='debito_credito')
    op.drop_index(op.f('ix_debito_credito_created_by_user'), table_name='debito_credito')
    op.drop_table('debito_credito')
    op.drop_table('roles')
    op.drop_index(op.f('ix_publicidad_medicos_medico_id'), table_name='publicidad_medicos')
    op.drop_table('publicidad_medicos')
    op.drop_table('permissions')
    op.drop_index('ix_noticias_publicada_fecha', table_name='noticias')
    op.drop_table('noticias')
    # ### end Alembic commands ###
