"""Correcion de Fk entre DetalleLiquidacion y DebitoCredito

Revision ID: 7fe681d4fdd9
Revises: 5611a8be8fb9
Create Date: 2025-09-07 19:18:09.047385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe681d4fdd9'
down_revision: Union[str, Sequence[str], None] = '5611a8be8fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
