"""init:modelos v1

Revision ID: 8623c97f5343
Revises: 
Create Date: 2025-07-25 10:09:11.527352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8623c97f5343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_concepto_descuento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_ref', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_ref')
    )
    op.create_table('listado_medico',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NRO_ESPECIALIDAD', sa.Integer(), nullable=False),
    sa.Column('NRO_ESPECIALIDAD2', sa.Integer(), nullable=False),
    sa.Column('NRO_ESPECIALIDAD3', sa.Integer(), nullable=False),
    sa.Column('NRO_ESPECIALIDAD4', sa.Integer(), nullable=False),
    sa.Column('NRO_ESPECIALIDAD5', sa.Integer(), nullable=False),
    sa.Column('NRO_SOCIO', sa.Integer(), nullable=False),
    sa.Column('NOMBRE', sa.String(length=40), nullable=False),
    sa.Column('DOMICILIO_CONSULTA', sa.String(length=100), nullable=True),
    sa.Column('TELEFONO_CONSULTA', sa.String(length=25), nullable=True),
    sa.Column('MATRICULA_PROV', sa.Integer(), nullable=False),
    sa.Column('MATRICULA_NAC', sa.Integer(), nullable=False),
    sa.Column('FECHA_RECIBIDO', sa.Date(), nullable=True),
    sa.Column('FECHA_MATRICULA', sa.Date(), nullable=True),
    sa.Column('FECHA_INGRESO', sa.Date(), nullable=True),
    sa.Column('DOMICILIO_PARTICULAR', sa.String(length=100), nullable=False),
    sa.Column('TELE_PARTICULAR', sa.String(length=15), nullable=False),
    sa.Column('CELULAR_PARTICULAR', sa.String(length=15), nullable=False),
    sa.Column('MAIL_PARTICULAR', sa.String(length=50), nullable=False),
    sa.Column('SEXO', sa.String(length=1), nullable=False),
    sa.Column('TIPO_DOC', sa.String(length=3), nullable=False),
    sa.Column('DOCUMENTO', sa.String(length=8), nullable=False),
    sa.Column('FECHA_NAC', sa.Date(), nullable=True),
    sa.Column('CUIT', sa.String(length=12), nullable=False),
    sa.Column('ANSSAL', sa.Integer(), nullable=False),
    sa.Column('VENCIMIENTO_ANSSAL', sa.Date(), nullable=True),
    sa.Column('MALAPRAXIS', sa.String(length=100), nullable=False),
    sa.Column('VENCIMIENTO_MALAPRAXIS', sa.Date(), nullable=True),
    sa.Column('MONOTRIBUTISTA', sa.String(length=2), nullable=False),
    sa.Column('FACTURA', sa.String(length=2), nullable=False),
    sa.Column('COBERTURA', sa.Integer(), nullable=False),
    sa.Column('VENCIMIENTO_COBERTURA', sa.Date(), nullable=True),
    sa.Column('PROVINCIA', sa.String(length=25), nullable=False),
    sa.Column('CODIGO_POSTAL', sa.String(length=15), nullable=False),
    sa.Column('VITALICIO', sa.String(length=1), nullable=False),
    sa.Column('FECHA_VITALICIO', sa.Date(), nullable=True),
    sa.Column('OBSERVACION', sa.String(length=200), nullable=False),
    sa.Column('CATEGORIA', sa.String(length=1), nullable=False),
    sa.Column('EXISTE', sa.String(length=1), nullable=False),
    sa.Column('NRO_ESPECIALIDAD6', sa.Integer(), nullable=False),
    sa.Column('EXCEP_DESDE', sa.String(length=6), nullable=False),
    sa.Column('EXCEP_HASTA', sa.String(length=6), nullable=False),
    sa.Column('EXCEP_DESDE2', sa.String(length=6), nullable=False),
    sa.Column('EXCEP_HASTA2', sa.String(length=6), nullable=False),
    sa.Column('EXCEP_DESDE3', sa.String(length=6), nullable=False),
    sa.Column('EXCEP_HASTA3', sa.String(length=6), nullable=False),
    sa.Column('INGRESAR', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD'), 'listado_medico', ['NRO_ESPECIALIDAD'], unique=False)
    op.create_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD2'), 'listado_medico', ['NRO_ESPECIALIDAD2'], unique=False)
    op.create_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD3'), 'listado_medico', ['NRO_ESPECIALIDAD3'], unique=False)
    op.create_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD4'), 'listado_medico', ['NRO_ESPECIALIDAD4'], unique=False)
    op.create_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD5'), 'listado_medico', ['NRO_ESPECIALIDAD5'], unique=False)
    op.create_index(op.f('ix_listado_medico_NRO_SOCIO'), 'listado_medico', ['NRO_SOCIO'], unique=False)
    op.create_table('obras_sociales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='——— WEPSSS ——— Versión del período; se incrementa al reabrir'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_debitado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_descontado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_lista_concepto_descuento', sa.Integer(), nullable=False),
    sa.Column('id_med', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lista_concepto_descuento'], ['lista_concepto_descuento.id'], ),
    sa.ForeignKeyConstraint(['id_med'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestaciones',
    sa.Column('id_prestacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('id_med', sa.Integer(), nullable=False),
    sa.Column('id_os', sa.Integer(), nullable=False),
    sa.Column('id_nomenclador', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('honorarios', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gastos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ayudante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_med'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['id_os'], ['obras_sociales.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id_prestacion')
    )
    op.create_table('debitos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_med', sa.Integer(), nullable=False),
    sa.Column('id_os', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('id_prestacion', sa.BigInteger(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_med'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['id_os'], ['obras_sociales.id'], ),
    sa.ForeignKeyConstraint(['id_prestacion'], ['prestaciones.id_prestacion'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debitos')
    op.drop_table('prestaciones')
    op.drop_table('descuentos')
    op.drop_table('periodos')
    op.drop_table('obras_sociales')
    op.drop_index(op.f('ix_listado_medico_NRO_SOCIO'), table_name='listado_medico')
    op.drop_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD5'), table_name='listado_medico')
    op.drop_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD4'), table_name='listado_medico')
    op.drop_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD3'), table_name='listado_medico')
    op.drop_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD2'), table_name='listado_medico')
    op.drop_index(op.f('ix_listado_medico_NRO_ESPECIALIDAD'), table_name='listado_medico')
    op.drop_table('listado_medico')
    op.drop_table('lista_concepto_descuento')
    # ### end Alembic commands ###
