"""weps

Revision ID: 87e304d32649
Revises: 1b9d8248844d
Create Date: 2025-09-08 11:32:41.673846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e304d32649'
down_revision: Union[str, Sequence[str], None] = '1b9d8248844d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_liq_res_os_per_v2'), 'liquidacion', type_='unique')
    op.create_unique_constraint('uq_liq_res_os_per_v2', 'liquidacion', ['resumen_id', 'obra_social_id', 'mes_periodo', 'anio_periodo', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_liq_res_os_per_v2', 'liquidacion', type_='unique')
    op.create_unique_constraint(op.f('uq_liq_res_os_per_v2'), 'liquidacion', ['resumen_id', 'obra_social_id', 'mes_periodo', 'anio_periodo'])
    # ### end Alembic commands ###
