"""cambios en la estructura de liquidacion

Revision ID: b92e3800591d
Revises: 
Create Date: 2026-01-14 11:38:47.843490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b92e3800591d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion_aplicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=False),
    sa.Column('aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', 'medico_id', 'descuento_id', name='uq_apl_per_med_desc')
    )
    op.create_index('idx_apl_per_med', 'deduccion_aplicacion', ['anio', 'mes', 'medico_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_anio'), 'deduccion_aplicacion', ['anio'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_created_by_user'), 'deduccion_aplicacion', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_descuento_id'), 'deduccion_aplicacion', ['descuento_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_medico_id'), 'deduccion_aplicacion', ['medico_id'], unique=False)
    op.create_index(op.f('ix_deduccion_aplicacion_mes'), 'deduccion_aplicacion', ['mes'], unique=False)
    op.create_table('deducciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=True),
    sa.Column('calculado_total', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_aplicado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('monto_aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('pagado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['listado_medico.ID'], ),
    sa.ForeignKeyConstraint(['descuento_id'], ['descuentos.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['listado_medico.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'anio', 'mes', 'descuento_id', name='uq_ded_med_per_desc')
    )
    op.create_index('idx_ded_med_per', 'deducciones', ['medico_id', 'anio', 'mes'], unique=False)
    op.create_index(op.f('ix_deducciones_anio'), 'deducciones', ['anio'], unique=False)
    op.create_index(op.f('ix_deducciones_created_by_user'), 'deducciones', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_deducciones_descuento_id'), 'deducciones', ['descuento_id'], unique=False)
    op.create_index(op.f('ix_deducciones_medico_id'), 'deducciones', ['medico_id'], unique=False)
    op.create_index(op.f('ix_deducciones_mes'), 'deducciones', ['mes'], unique=False)
    op.drop_table('tmp_socio_servicios')
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=mysql.VARCHAR(length=66),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=8, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=69),
               type_=sa.String(length=100, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=mysql.VARCHAR(length=23),
               type_=sa.String(length=25, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=15, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               type_=sa.String(length=6, collation='utf8_spanish2_ci'),
               nullable=False)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False,
               comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR',
               existing_comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación')
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index('CATEGORIA', 'listado_medico', ['CATEGORIA'], unique=False)
    op.create_index('NRO_ESPECIALIDAD', 'listado_medico', ['NRO_ESPECIALIDAD'], unique=False)
    op.create_index('NRO_ESPECIALIDAD2', 'listado_medico', ['NRO_ESPECIALIDAD2'], unique=False)
    op.create_index('NRO_ESPECIALIDAD3', 'listado_medico', ['NRO_ESPECIALIDAD3'], unique=False)
    op.create_index('NRO_ESPECIALIDAD4', 'listado_medico', ['NRO_ESPECIALIDAD4'], unique=False)
    op.create_index('NRO_ESPECIALIDAD5', 'listado_medico', ['NRO_ESPECIALIDAD5'], unique=False)
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('periodos_doctor', 'USUARIO')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodos_doctor', sa.Column('USUARIO', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index('NRO_ESPECIALIDAD5', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD4', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD3', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD2', table_name='listado_medico')
    op.drop_index('NRO_ESPECIALIDAD', table_name='listado_medico')
    op.drop_index('CATEGORIA', table_name='listado_medico')
    op.alter_column('listado_medico', 'FECHA_VITALICIO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_COBERTURA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_MALAPRAXIS',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'VENCIMIENTO_ANSSAL',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_NAC',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_INGRESO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_MATRICULA',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'FECHA_RECIBIDO',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('listado_medico', 'INGRESAR',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True,
               comment='E=empleados / D=médicos / C=contable / S=superadministrador / A=aduditoria / F=facturación / L=liquidación',
               existing_comment='D=DOCTOR / E=EMPLEADOS DEL COLEGIO / A ADMINISTRADOR')
    op.alter_column('listado_medico', 'EXCEP_HASTA3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE3',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf32', collation='utf32_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE2',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_HASTA',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'EXCEP_DESDE',
               existing_type=sa.String(length=6, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD6',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'EXISTE',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CATEGORIA',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'OBSERVACION',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('listado_medico', 'VITALICIO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'CODIGO_POSTAL',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'PROVINCIA',
               existing_type=sa.String(length=25, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=23),
               nullable=True)
    op.alter_column('listado_medico', 'COBERTURA',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'FACTURA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MONOTRIBUTISTA',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('listado_medico', 'MALAPRAXIS',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=69),
               nullable=True)
    op.alter_column('listado_medico', 'ANSSAL',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'CUIT',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('listado_medico', 'DOCUMENTO',
               existing_type=sa.String(length=8, collation='utf8_spanish2_ci'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TIPO_DOC',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('listado_medico', 'SEXO',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('listado_medico', 'MAIL_PARTICULAR',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('listado_medico', 'CELULAR_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('listado_medico', 'TELE_PARTICULAR',
               existing_type=sa.String(length=15, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_PARTICULAR',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(length=66),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_NAC',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'MATRICULA_PROV',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'TELEFONO_CONSULTA',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('listado_medico', 'DOMICILIO_CONSULTA',
               existing_type=sa.String(length=100, collation='utf8_spanish2_ci'),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_spanish_ci', length=103),
               nullable=True)
    op.alter_column('listado_medico', 'NOMBRE',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_SOCIO',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('listado_medico', 'NRO_ESPECIALIDAD',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_table('tmp_socio_servicios',
    sa.Column('nro_socio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descuento_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('nro_socio', 'descuento_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_deducciones_mes'), table_name='deducciones')
    op.drop_index(op.f('ix_deducciones_medico_id'), table_name='deducciones')
    op.drop_index(op.f('ix_deducciones_descuento_id'), table_name='deducciones')
    op.drop_index(op.f('ix_deducciones_created_by_user'), table_name='deducciones')
    op.drop_index(op.f('ix_deducciones_anio'), table_name='deducciones')
    op.drop_index('idx_ded_med_per', table_name='deducciones')
    op.drop_table('deducciones')
    op.drop_index(op.f('ix_deduccion_aplicacion_mes'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_medico_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_descuento_id'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_created_by_user'), table_name='deduccion_aplicacion')
    op.drop_index(op.f('ix_deduccion_aplicacion_anio'), table_name='deduccion_aplicacion')
    op.drop_index('idx_apl_per_med', table_name='deduccion_aplicacion')
    op.drop_table('deduccion_aplicacion')
    # ### end Alembic commands ###
