"""add liquidaciones

Revision ID: bd97d8d8a50d
Revises: 54eac0372e3f
Create Date: 2025-08-18 15:40:23.341168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd97d8d8a50d'
down_revision: Union[str, Sequence[str], None] = '54eac0372e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nro_debito', sa.String(length=16), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debito_nro_debito'), 'debito', ['nro_debito'], unique=True)
    op.create_table('liquidacion_resumen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('nros_liquidacion', sa.Text(), nullable=True),
    sa.Column('total_bruto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_debitos', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_deduccion', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('a', 'c', 'e', name='liqres_estado'), nullable=False),
    sa.Column('cierre_timestamp', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=True),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('nro_liquidacion', sa.String(length=30), nullable=True),
    sa.Column('total_bruto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_debitos', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_neto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['resumen_id'], ['liquidacion_resumen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resumen_id', 'obra_social_id', 'periodo', name='uq_liq_res_os_per')
    )
    op.create_index(op.f('ix_liquidacion_obra_social_id'), 'liquidacion', ['obra_social_id'], unique=False)
    op.create_index(op.f('ix_liquidacion_periodo'), 'liquidacion', ['periodo'], unique=False)
    op.create_table('detalle_liquidacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('prestacion_id', sa.String(length=16), nullable=False),
    sa.Column('debito_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('bruto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('debito_monto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('deduccion_monto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('neto', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['debito_id'], ['debito.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestacion_id', name='uq_det_prestacion')
    )
    op.create_index('idx_det_os_per_med', 'detalle_liquidacion', ['obra_social_id', 'periodo', 'medico_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_liquidacion_id'), 'detalle_liquidacion', ['liquidacion_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_medico_id'), 'detalle_liquidacion', ['medico_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_obra_social_id'), 'detalle_liquidacion', ['obra_social_id'], unique=False)
    op.create_index(op.f('ix_detalle_liquidacion_periodo'), 'detalle_liquidacion', ['periodo'], unique=False)
    op.drop_index(op.f('cod_ref'), table_name='lista_concepto_descuento')
    op.drop_table('lista_concepto_descuento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_concepto_descuento',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_ref', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('porcentaje', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('cod_ref'), 'lista_concepto_descuento', ['cod_ref'], unique=True)
    op.drop_index(op.f('ix_detalle_liquidacion_periodo'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_obra_social_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_medico_id'), table_name='detalle_liquidacion')
    op.drop_index(op.f('ix_detalle_liquidacion_liquidacion_id'), table_name='detalle_liquidacion')
    op.drop_index('idx_det_os_per_med', table_name='detalle_liquidacion')
    op.drop_table('detalle_liquidacion')
    op.drop_index(op.f('ix_liquidacion_periodo'), table_name='liquidacion')
    op.drop_index(op.f('ix_liquidacion_obra_social_id'), table_name='liquidacion')
    op.drop_table('liquidacion')
    op.drop_table('liquidacion_resumen')
    op.drop_index(op.f('ix_debito_nro_debito'), table_name='debito')
    op.drop_table('debito')
    # ### end Alembic commands ###
