"""Cambios

Revision ID: be42759d37e9
Revises: 4d1a387f49c3
Create Date: 2025-09-19 10:31:49.232628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be42759d37e9'
down_revision: Union[str, Sequence[str], None] = '4d1a387f49c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodos', 'USUARIO',
               existing_type=mysql.INTEGER(display_width=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
