"""cambios recientes

Revision ID: e6650ac0a460
Revises: 7457cb1aad50
Create Date: 2025-09-14 14:44:42.655416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6650ac0a460'
down_revision: Union[str, Sequence[str], None] = '7457cb1aad50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deducciones_colegio', sa.Column('monto_aplicado', sa.DECIMAL(precision=14, scale=2), nullable=False))
    op.add_column('deducciones_colegio', sa.Column('porcentaje_aplicado', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_index(op.f('uq_med_res_des'), table_name='deducciones_colegio')
    op.drop_index(op.f('uq_med_res_esp'), table_name='deducciones_colegio')
    op.create_index(op.f('ix_deducciones_colegio_descuento_id'), 'deducciones_colegio', ['descuento_id'], unique=False)
    op.create_index(op.f('ix_deducciones_colegio_especialidad_id'), 'deducciones_colegio', ['especialidad_id'], unique=False)
    op.create_unique_constraint('uq_med_res_desc', 'deducciones_colegio', ['medico_id', 'resumen_id', 'descuento_id'])
    op.create_unique_constraint('uq_med_res_esp2', 'deducciones_colegio', ['medico_id', 'resumen_id', 'especialidad_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_med_res_esp2', 'deducciones_colegio', type_='unique')
    op.drop_constraint('uq_med_res_desc', 'deducciones_colegio', type_='unique')
    op.drop_index(op.f('ix_deducciones_colegio_especialidad_id'), table_name='deducciones_colegio')
    op.drop_index(op.f('ix_deducciones_colegio_descuento_id'), table_name='deducciones_colegio')
    op.create_index(op.f('uq_med_res_esp'), 'deducciones_colegio', ['medico_id', 'resumen_id', 'especialidad_id'], unique=True)
    op.create_index(op.f('uq_med_res_des'), 'deducciones_colegio', ['medico_id', 'resumen_id', 'descuento_id'], unique=True)
    op.drop_column('deducciones_colegio', 'porcentaje_aplicado')
    op.drop_column('deducciones_colegio', 'monto_aplicado')
    # ### end Alembic commands ###
